TERRAIN_CONSTANTS = [
    {"id": 0, "name": "GRASS", "description": "Grass 1", "comments": "default terrain"},
    {
        "id": 1,
        "name": "WATER",
        "description": "Water, Shallow",
        "comments": "normal water",
    },
    {
        "id": 2,
        "name": "BEACH",
        "description": "Beach",
        "comments": "automatically placed when land terrains border water",
    },
    {"id": 3, "name": "DIRT3", "description": "Dirt 3", "comments": "grassy"},
    {
        "id": 4,
        "name": "SHALLOW",
        "description": "Shallows",
        "comments": "can be used to create river crossings",
    },
    {
        "id": 5,
        "name": "LEAVES",
        "description": "Underbrush",
        "comments": "used as the underlying texture for many forest types",
    },
    {
        "id": 6,
        "name": "DIRT",
        "description": "Dirt 1",
        "comments": "brown with the occasional cactus",
    },
    {"id": 7, "name": None, "description": "Farm", "comments": "no food"},
    {"id": 8, "name": None, "description": "Farm, Dead", "comments": "no food"},
    {"id": 9, "name": "GRASS3", "description": "Grass 3", "comments": "brownish grass"},
    {
        "id": 10,
        "name": "FOREST",
        "description": "Forest, Oak",
        "comments": "placed on LEAVES",
    },
    {
        "id": 11,
        "name": "DIRT2",
        "description": "Dirt 2",
        "comments": "dirt/grass mixture",
    },
    {
        "id": 12,
        "name": "GRASS2",
        "description": "Grass 2",
        "comments": "very green grass",
    },
    {
        "id": 13,
        "name": "PALM_DESERT",
        "description": "Forest, Palm Desert",
        "comments": "placed on DESERT",
    },
    {
        "id": 14,
        "name": "DESERT",
        "description": "Desert, Sand",
        "comments": "sandy and light colored",
    },
    {
        "id": 15,
        "name": None,
        "description": "Water 2D, Shoreless",
        "comments": "looks like WATER; no beaches; not dockable",
    },
    {
        "id": 16,
        "name": "ROCK1",
        "description": "Grass, Other",
        "comments": "looks like GRASS; automatically placed under cliffs",
    },
    {
        "id": 17,
        "name": "JUNGLE",
        "description": "Forest, Jungle",
        "comments": "placed on LEAVES",
    },
    {
        "id": 18,
        "name": "BAMBOO",
        "description": "Forest, Bamboo",
        "comments": "placed on LEAVES",
    },
    {
        "id": 19,
        "name": "PINE_FOREST",
        "description": "Forest, Pine",
        "comments": "placed on LEAVES",
    },
    {
        "id": 20,
        "name": None,
        "description": "Forest, Oak Bush",
        "comments": "placed on LEAVES",
    },
    {
        "id": 21,
        "name": "SNOW_FOREST",
        "description": "Forest, Pine Snow",
        "comments": "placed on underbrush snow",
    },
    {
        "id": 22,
        "name": "DEEP_WATER",
        "description": "Water, Deep",
        "comments": "not dockable",
    },
    {
        "id": 23,
        "name": "MED_WATER",
        "description": "Water, Medium",
        "comments": "not dockable",
    },
    {
        "id": 24,
        "name": "ROAD",
        "description": "Road",
        "comments": "clean road; cannot place natural resources",
    },
    {
        "id": 25,
        "name": "ROAD2",
        "description": "Road, Broken",
        "comments": "road with dirt patches; cannot place natural resources",
    },
    {
        "id": 26,
        "name": None,
        "description": "Ice, Navigable",
        "comments": "looks like ICE",
    },
    {
        "id": 27,
        "name": None,
        "description": "Grass, Foundation",
        "comments": "looks like DIRT2; no beaches; still dockable; foundation terrain for buildings",
    },
    {
        "id": 28,
        "name": None,
        "description": "Water 2D, Bridge",
        "comments": "no beaches; produced by bridge objects; acts as a land terrain",
    },
    {"id": 29, "name": None, "description": "Farm, 0%", "comments": "no food"},
    {"id": 30, "name": None, "description": "Farm, 33%", "comments": "no food"},
    {"id": 31, "name": None, "description": "Farm, 67%", "comments": "no food"},
    {
        "id": 32,
        "name": "SNOW",
        "description": "Snow",
        "comments": "icy beach when bordering water",
    },
    {
        "id": 33,
        "name": "DIRT_SNOW",
        "description": "OBSOLETE: Snow Grass",
        "comments": "icy beach when bordering water; cannot be layered",
    },
    {
        "id": 34,
        "name": "GRASS_SNOW",
        "description": "OBSOLETE: Snow Dirt",
        "comments": "icy beach when bordering water; cannot be layered",
    },
    {
        "id": 35,
        "name": "ICE",
        "description": "Ice",
        "comments": "cannot place natural resources",
    },
    {
        "id": 36,
        "name": None,
        "description": "Snow, Foundation",
        "comments": "looks like SNOW_DIRT; no beaches; still dockable; foundation terrain for buildings on snowy terrains; cannot be layered",
    },
    {
        "id": 37,
        "name": " ICYSHORE",
        "description": "Beach, Ice",
        "comments": "created when snowy terrains border water; looks different from other ice terrains",
    },
    {
        "id": 38,
        "name": None,
        "description": "OBSOLETE: Road, Snow",
        "comments": "road with dirt and snow patches; cannot place natural resources; cannot be layered",
    },
    {
        "id": 39,
        "name": None,
        "description": "OBSOLETE: Road, Fungus",
        "comments": "road with dirt and grass patches; cannot place natural resources; cannot be layered",
    },
    {
        "id": 40,
        "name": "DLC_ROCK",
        "description": "Rock 1",
        "comments": "used for King of the Hill; cannot place natural resources",
    },
    {
        "id": 41,
        "name": "DLC_SAVANNAH",
        "description": "Dirt, Savannah",
        "comments": "light brown",
    },
    {
        "id": 42,
        "name": "DLC_DIRT4",
        "description": "Dirt 4",
        "comments": "dirt with some grass",
    },
    {
        "id": 43,
        "name": "DLC_DRYROAD",
        "description": "OBSOLETE: Road, Desert",
        "comments": "road with sand patches; cannot place natural resources; cannot be layered",
    },
    {
        "id": 44,
        "name": "DLC_MOORLAND",
        "description": "OBSOLETE: Dirt, Mud",
        "comments": "mud with some grass; cannot be layered",
    },
    {
        "id": 45,
        "name": "DLC_CRACKED",
        "description": "Desert, Cracked",
        "comments": "buildings take 25% more damage",
    },
    {
        "id": 46,
        "name": "DLC_QUICKSAND",
        "description": "Desert, Quicksand",
        "comments": "cannot place natural resources",
    },
    {
        "id": 47,
        "name": "DLC_BLACK",
        "description": "Black",
        "comments": "completely black; units have buggy pathfinding when trying to cross",
    },
    {
        "id": 48,
        "name": "DLC_DRAGONFOREST",
        "description": "Forest, Dragon Tree",
        "comments": "placed on DIRT",
    },
    {
        "id": 49,
        "name": "DLC_BAOBABFOREST",
        "description": "Forest, Baobab",
        "comments": "200 wood per tree; 25% tree density; placed on DLC_DIRT4",
    },
    {
        "id": 50,
        "name": "DLC_ACACIAFOREST",
        "description": "Forest, Acacia",
        "comments": "150 wood per tree; 50% tree density; placed on DLC_SAVANNAH",
    },
    {
        "id": 51,
        "name": "DLC_BEACH2",
        "description": "Beach, White, Vegatation",
        "comments": "alternative beach terrain",
    },
    {
        "id": 52,
        "name": "DLC_BEACH3",
        "description": "Beach, Vegetation",
        "comments": "alternative beach terrain",
    },
    {
        "id": 53,
        "name": "DLC_BEACH4",
        "description": "Beach, White",
        "comments": "alternative beach terrain",
    },
    {
        "id": 54,
        "name": "DLC_MANGROVESHALLOW",
        "description": "Shallows, Mangrove",
        "comments": "light blue with mangrove roots",
    },
    {
        "id": 55,
        "name": "DLC_MANGROVEFOREST",
        "description": "Forest, Mangrove",
        "comments": "80% tree density; placed on DLC_MANGROVESHALLOW",
    },
    {
        "id": 56,
        "name": "DLC_RAINFOREST",
        "description": "Forest, Rainforest",
        "comments": "placed on underbrush jungle",
    },
    {
        "id": 57,
        "name": "DLC_WATER4",
        "description": "Water, Deep Ocean",
        "comments": "not dockable; darker than DEEP_WATER",
    },
    {
        "id": 58,
        "name": "DLC_WATER5",
        "description": "Water, Azure",
        "comments": "brighter than WATER",
    },
    {
        "id": 59,
        "name": "DLC_NEWSHALLOW",
        "description": "Shallows, Azure",
        "comments": "bright blue",
    },
    {
        "id": 60,
        "name": "DLC_JUNGLEGRASS",
        "description": "Grass, Jungle",
        "comments": "dark green",
    },
    {
        "id": 61,
        "name": "DLC_JUNGLEROAD",
        "description": "OBSOLETE: Road, Jungle",
        "comments": "road covered in grass; no resource restrictions; cannot be layered",
    },
    {
        "id": 62,
        "name": "DLC_JUNGLELEAVES",
        "description": "OBSOLETE: Underbrush, Jungle",
        "comments": "jungle grass with leafy patches; cannot be layered",
    },
    {"id": 63, "name": None, "description": "Rice Farm", "comments": "no food"},
    {"id": 64, "name": None, "description": "Rice Farm, Dead", "comments": "no food"},
    {"id": 65, "name": None, "description": "Rice Farm, 0%", "comments": "no food"},
    {"id": 66, "name": None, "description": "Rice Farm, 33%", "comments": "no food"},
    {"id": 67, "name": None, "description": "Rice Farm, 66%", "comments": "no food"},
    {
        "id": 68,
        "name": None,
        "description": "Unused Land 68",
        "comments": "uses the classic grass texture from AoC",
    },
    {
        "id": 69,
        "name": None,
        "description": "Corruption",
        "comments": "used for battle royale; visible through fog of war; does not cause damage; makes farms invisible; units have buggy pathfinding when trying to cross",
    },
    {
        "id": 70,
        "name": None,
        "description": "Gravel, Default",
        "comments": "gray gravel",
    },
    {
        "id": 71,
        "name": None,
        "description": "Underbrush, Leaves",
        "comments": "more leafy than LEAVES",
    },
    {
        "id": 72,
        "name": None,
        "description": "Underbrush, Snow",
        "comments": "used for snowy forest terrains",
    },
    {
        "id": 73,
        "name": None,
        "description": "Snow, Light",
        "comments": "snow that layers weakly with terrain_mask",
    },
    {
        "id": 74,
        "name": None,
        "description": "Snow, Strong",
        "comments": "snow that layers strongly with terrain_mask",
    },
    {
        "id": 75,
        "name": None,
        "description": "Road, Fungus",
        "comments": "very mossy road; no resource restrictions",
    },
    {"id": 76, "name": None, "description": "Dirt, Mud", "comments": "brown mud"},
    {
        "id": 77,
        "name": None,
        "description": "Underbrush, Jungle",
        "comments": "greenish leaves",
    },
    {
        "id": 78,
        "name": None,
        "description": "Road, Gravel",
        "comments": "road with gravel; no resource restrictions",
    },
    {
        "id": 79,
        "name": None,
        "description": "Beach (Non-Navigable)",
        "comments": "looks like BEACH; acts as a land terrain",
    },
    {
        "id": 80,
        "name": None,
        "description": "Beach (Non-Navigable), Wet Sand",
        "comments": "looks like DLC_WETBEACH; acts as a land terrain",
    },
    {
        "id": 81,
        "name": None,
        "description": "Beach (Non-Navigable), Wet Gravel",
        "comments": "looks like DLC_GRAVELBEACH; acts as a land terrain",
    },
    {
        "id": 82,
        "name": None,
        "description": "Beach (Non-Navigable), Wet Rock",
        "comments": "looks like DLC_WETROCKBEACH; acts as a land terrain",
    },
    {
        "id": 83,
        "name": None,
        "description": "Grass, Jungle (Rainforest)",
        "comments": "dark green; like DLC_JUNGLEGRASS but with slightly different plant coverage",
    },
    {
        "id": 84,
        "name": None,
        "description": "Moddable Land 84",
        "comments": "uses placeholder texture",
    },
    {
        "id": 85,
        "name": None,
        "description": "Moddable Land 85",
        "comments": "uses placeholder texture",
    },
    {
        "id": 86,
        "name": None,
        "description": "Moddable Land 86",
        "comments": "uses placeholder texture",
    },
    {
        "id": 87,
        "name": None,
        "description": "Moddable Land 87",
        "comments": "uses placeholder texture",
    },
    {
        "id": 88,
        "name": "MEDITERRANEAN_FOREST",
        "description": "Forest, Mediteranean",
        "comments": "mixture of cypress, olive and italian pine trees; placed on LEAVES",
    },
    {
        "id": 89,
        "name": None,
        "description": "Forest, Bush",
        "comments": "bushes; placed on LEAVES",
    },
    {
        "id": 90,
        "name": None,
        "description": "Forest, Reeds (Shallows)",
        "comments": "50 wood per tree; placed on SHALLOW; looks like SHALLOW on the minimap",
    },
    {
        "id": 91,
        "name": "DLC_REEDSBEACH",
        "description": "Forest, Reeds (Beach)",
        "comments": "50 wood per tree; placed on DLC_WETBEACH",
    },
    {
        "id": 92,
        "name": None,
        "description": "Forest, Reeds",
        "comments": "50 wood per tree; placed on LEAVES",
    },
    {
        "id": 93,
        "name": None,
        "description": "Moddable Walkable Shallows 93",
        "comments": "uses placeholder texture",
    },
    {
        "id": 94,
        "name": None,
        "description": "Moddable Walkable Shallows 94",
        "comments": "uses placeholder texture",
    },
    {"id": 95, "name": None, "description": "Water, Green", "comments": "dockable"},
    {"id": 96, "name": None, "description": "Water, Brown", "comments": "dockable"},
    {
        "id": 97,
        "name": None,
        "description": "Moddable Water 97",
        "comments": "uses placeholder texture; not dockable",
    },
    {
        "id": 98,
        "name": None,
        "description": "Moddable Water 98",
        "comments": "uses placeholder texture; not dockable",
    },
    {
        "id": 99,
        "name": None,
        "description": "Moddable Deep Water 99",
        "comments": "uses placeholder texture; not dockable",
    },
    {
        "id": 100,
        "name": "DLC_DRYGRASS",
        "description": "Grass, Dry",
        "comments": "brownish grass",
    },
    {
        "id": 101,
        "name": "DLC_BOGLAND",
        "description": "Swamp, Bogland",
        "comments": "blueish grass; cannot place natural resources",
    },
    {
        "id": 102,
        "name": "DLC_DESERTGRAVEL",
        "description": "Gravel, Desert",
        "comments": "lighter version of gravel",
    },
    {
        "id": 103,
        "name": "DLC_ROADGRAVEL",
        "description": "OBSOLETE: Road, Gravel",
        "comments": "gravel road with dirt patches; no resource restrictions; cannot be layered",
    },
    {
        "id": 104,
        "name": "DLC_FORESTAUTUMN",
        "description": "Forest, Autumn",
        "comments": "placed on LEAVES",
    },
    {
        "id": 105,
        "name": "DLC_FORESTSNOWAUTUMN",
        "description": "Forest, Autumn Snow",
        "comments": "snowy version of DLC_FORESTAUTUMN; placed on underbrush snow",
    },
    {
        "id": 106,
        "name": "DLC_FORESTDEAD",
        "description": "Forest, Dead",
        "comments": "snowy bushes and dead trees; placed on underbrush snow",
    },
    {
        "id": 107,
        "name": "DLC_WETBEACH",
        "description": "Beach, Wet",
        "comments": "alternative beach terrain",
    },
    {
        "id": 108,
        "name": "DLC_GRAVELBEACH",
        "description": "Beach, Wet Gravel",
        "comments": "alternative beach terrain",
    },
    {
        "id": 109,
        "name": "DLC_WETROCKBEACH",
        "description": "Beach, Wet Rock",
        "comments": "alternative beach terrain",
    },
    {
        "id": 110,
        "name": "BIRCH_FOREST",
        "description": "Forest, Birch",
        "comments": "placed on LEAVES",
    },
    {
        "id": 111,
        "name": "MUDDY_SHALLOW",
        "description": "Swamp, Shallows",
        "comments": "acts like SHALLOW",
    },
    {
        "id": 112,
        "name": "PALM_GRASS_FOREST",
        "description": "Forest, Palm Grass",
        "comments": "like PALM_DESERT, but placed on GRASS2",
    },
    {
        "id": 113,
        "name": "LUSH_BAMBOO_FOREST",
        "description": "Forest, Lush Bamboo",
        "comments": "placed on underbrush jungle",
    },
    {
        "id": 114,
        "name": "YELLOW_SHALLOW_WATER",
        "description": "Water, Yellow (Shallow)",
        "comments": "dockable",
    },
    {
        "id": 115,
        "name": "YELLOW_SHALLOW",
        "description": "Shallows, Yellow",
        "comments": "acts like SHALLOW",
    },
    {
        "id": 116,
        "name": "YELLOW_DEEP_WATER",
        "description": "Water, Yellow (Deep)",
        "comments": "not dockable",
    },
    {"id": 117, "name": None, "description": "Pasture", "comments": "no food"},
    {"id": 118, "name": None, "description": "Pasture, Dead", "comments": "no food"},
    {"id": 119, "name": None, "description": "Pasture, 0%", "comments": "no food"},
    {"id": 120, "name": None, "description": "Pasture, 33%", "comments": "no food"},
    {"id": 121, "name": None, "description": "Pasture, 66%", "comments": "no food"},
    {"id": 122, "name": None, "description": "Unused 122", "comments": None},
    {"id": 123, "name": None, "description": "Unused 123", "comments": None},
    {"id": 124, "name": None, "description": "Unused 124", "comments": None},
    {"id": 125, "name": None, "description": "Unused 125", "comments": None},
    {"id": 126, "name": None, "description": "Unused 126", "comments": None},
    {"id": 127, "name": None, "description": "Unused 127", "comments": None},
    {"id": 128, "name": None, "description": "Unused 128", "comments": None},
    {"id": 129, "name": None, "description": "Unused 129", "comments": None},
    {"id": 130, "name": None, "description": "Unused 130", "comments": None},
    {"id": 131, "name": None, "description": "Unused 131", "comments": None},
    {"id": 132, "name": None, "description": "Unused 132", "comments": None},
    {"id": 133, "name": None, "description": "Unused 133", "comments": None},
    {"id": 134, "name": None, "description": "Unused 134", "comments": None},
    {"id": 135, "name": None, "description": "Unused 135", "comments": None},
    {"id": 136, "name": None, "description": "Unused 136", "comments": None},
    {"id": 137, "name": None, "description": "Unused 137", "comments": None},
    {"id": 138, "name": None, "description": "Unused 138", "comments": None},
    {"id": 139, "name": None, "description": "Unused 139", "comments": None},
    {"id": 140, "name": None, "description": "Unused 140", "comments": None},
    {"id": 141, "name": None, "description": "Unused 141", "comments": None},
    {"id": 142, "name": None, "description": "Unused 142", "comments": None},
    {"id": 143, "name": None, "description": "Unused 143", "comments": None},
    {"id": 144, "name": None, "description": "Unused 144", "comments": None},
    {"id": 145, "name": None, "description": "Unused 145", "comments": None},
    {"id": 146, "name": None, "description": "Unused 146", "comments": None},
    {"id": 147, "name": None, "description": "Unused 147", "comments": None},
    {"id": 148, "name": None, "description": "Unused 148", "comments": None},
    {"id": 149, "name": None, "description": "Unused 149", "comments": None},
    {"id": 150, "name": None, "description": "Unused 150", "comments": None},
    {"id": 151, "name": None, "description": "Unused 151", "comments": None},
    {"id": 152, "name": None, "description": "Unused 152", "comments": None},
    {"id": 153, "name": None, "description": "Unused 153", "comments": None},
    {"id": 154, "name": None, "description": "Unused 154", "comments": None},
    {"id": 155, "name": None, "description": "Unused 155", "comments": None},
    {"id": 156, "name": None, "description": "Unused 156", "comments": None},
    {"id": 157, "name": None, "description": "Unused 157", "comments": None},
    {"id": 158, "name": None, "description": "Unused 158", "comments": None},
    {"id": 159, "name": None, "description": "Unused 159", "comments": None},
    {"id": 160, "name": None, "description": "Unused 160", "comments": None},
    {"id": 161, "name": None, "description": "Unused 161", "comments": None},
    {"id": 162, "name": None, "description": "Unused 162", "comments": None},
    {"id": 163, "name": None, "description": "Unused 163", "comments": None},
    {"id": 164, "name": None, "description": "Unused 164", "comments": None},
    {"id": 165, "name": None, "description": "Unused 165", "comments": None},
    {"id": 166, "name": None, "description": "Unused 166", "comments": None},
    {"id": 167, "name": None, "description": "Unused 167", "comments": None},
    {"id": 168, "name": None, "description": "Unused 168", "comments": None},
    {"id": 169, "name": None, "description": "Unused 169", "comments": None},
    {"id": 170, "name": None, "description": "Unused 170", "comments": None},
    {"id": 171, "name": None, "description": "Unused 171", "comments": None},
    {"id": 172, "name": None, "description": "Unused 172", "comments": None},
    {"id": 173, "name": None, "description": "Unused 173", "comments": None},
    {"id": 174, "name": None, "description": "Unused 174", "comments": None},
    {"id": 175, "name": None, "description": "Unused 175", "comments": None},
    {"id": 176, "name": None, "description": "Unused 176", "comments": None},
    {"id": 177, "name": None, "description": "Unused 177", "comments": None},
    {"id": 178, "name": None, "description": "Unused 178", "comments": None},
    {"id": 179, "name": None, "description": "Unused 179", "comments": None},
    {"id": 180, "name": None, "description": "Unused 180", "comments": None},
    {"id": 181, "name": None, "description": "Unused 181", "comments": None},
    {"id": 182, "name": None, "description": "Unused 182", "comments": None},
    {"id": 183, "name": None, "description": "Unused 183", "comments": None},
    {"id": 184, "name": None, "description": "Unused 184", "comments": None},
    {"id": 185, "name": None, "description": "Unused 185", "comments": None},
    {"id": 186, "name": None, "description": "Unused 186", "comments": None},
    {"id": 187, "name": None, "description": "Unused 187", "comments": None},
    {"id": 188, "name": None, "description": "Unused 188", "comments": None},
    {"id": 189, "name": None, "description": "Unused 189", "comments": None},
    {"id": 190, "name": None, "description": "Unused 190", "comments": None},
    {"id": 191, "name": None, "description": "Unused 191", "comments": None},
    {"id": 192, "name": None, "description": "Unused 192", "comments": None},
    {"id": 193, "name": None, "description": "Unused 193", "comments": None},
    {"id": 194, "name": None, "description": "Unused 194", "comments": None},
    {"id": 195, "name": None, "description": "Unused 195", "comments": None},
    {"id": 196, "name": None, "description": "Unused 196", "comments": None},
    {"id": 197, "name": None, "description": "Unused 197", "comments": None},
    {"id": 198, "name": None, "description": "Unused 198", "comments": None},
    {"id": 199, "name": None, "description": "Unused 199", "comments": None},
]
